### ISSUE TITLE
Créer un serveur graphdb hors prod pour rdfi (pour branchement de metadata-api interne)

### ISSUE THREAD

**Issue by EmmanuelDemey** [InseeFr/Metadata-API#109]
Est-ce que ce n'est pas déjà fait ?

**Comment by EmmanuelDemey** [comment]
@FBibonne  qu'en est-il de ce ticket ?

**Comment by FBibonne** [comment]
Ok. il y a un repo dédié sur un serveur rdf de hors prod. Donc c'est fait
