### ISSUE TITLE
Mettre en place metadata-api sur le portail des apis

### ISSUE THREAD

**Issue by JeromeMBourgeois** [InseeFr/Metadata-API#119]
- [x] Vérifier le paramétrage de l'api sur gravitee
- [x] Lancer un test de charge sur l'api en preprod pour vérifier les métriques
- [x] regarder si des documents au format markdown peuvent être utilisés
- [x] étudier et mettre en place si nécessaire un jeton API pour des clients "importants"

**Comment by PierreVasseur** [comment]
Paramétrage de Metadata API finalisé sur le nouveau portail des API : https://portail-api.insee.fr/catalog/api/5029cf12-e930-4d24-a9cf-12e9307d241d?aq=ALL

Bascule demandée le 07/10 à l'équipe réseau pour que les utilisateurs externes de Metadata API soient dirigés vers Gravitee plutôt que WSO2, afin de vérifier le bon fonctionnement de Gravitee avant la mort de WSO2 prévue le 15/10/2024, avec retour en arrière possible s'il y a un souci

Reste à alimenter le portail avec la documentation souhaitée (en format markdown, ou en format PDF disponible avec des liens de téléchargement)
