### ISSUE TITLE
Adapter GET/listeCode/{id}

### ISSUE THREAD

**Issue by EmmanuelDemey** [InseeFr/Metadata-API#85]

**Comment by flo7894** [comment]
Il semble y avoir un problème sur la méthode.
L'ensemble des codes de la listes devrait être listés comme un array avec une propriété "codes", pour chaque code en cas de présence d'un prédicat skos:exactMatch (ou skos:closeMatch) du code vers un  code alternatif, on devrait avoir un array sur le code avec la propriété "codesEquivalents"

En pj un exemple de fichier trig d'une code liste, et le fichier json qu'on attendrait en retour

[TRIG-recette-liste-2023-09-22.txt](https://github.com/InseeFr/Metadata-API/files/12700076/TRIG-recette-liste-2023-09-22.txt)

[JSON-recette-liste-2023-09-22.txt](https://github.com/InseeFr/Metadata-API/files/12700077/JSON-recette-liste-2023-09-22.txt)

**Comment by HugoBouttes** [comment]
Il me semble que ça devrait plutôt être une Issue Magma non ? Je vais créer la même issue sur Magma
